name: Build and Deploy Docs
on:
  push:
    branches: [ docs-build ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material 'mkdocstrings[python]' mkdocs-gen-files
      # Install your packages so mkdocstrings can import them
      - run: pip install -e sdk
      - run: pip install -e instrumentation-packages/codon-instrumentation-langgraph
      - run: mkdocs build
      - uses: actions/deploy-pages@v2
        with:
          path: ./site